# نام ورک‌فلو
name: Build and Release for Broadlink NG

# تریگرها
on:
  # اجرای دستی با قابلیت دیباگ از طریق SSH
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions for debugging'
        required: false
        default: 'false'
        type: 'boolean'
  # اجرا در زمان پوش به شاخه main
  push:
    branches:
      - 'main'

# --- دادن دسترسی نوشتن به ورک‌فلو برای ساخت Release ---
permissions:
  contents: write

env:
  TZ: Asia/Tehran
  # نام پوشه پکیج شما
  PACKAGE_DIR: luci-app-broadlink-ng

jobs:
  # --- جاب اول: بررسی نسخه و ساخت Release ---
  check_and_release:
    name: Check Version and Create Release
    runs-on: ubuntu-latest
    outputs:
      new_version_tag: ${{ steps.check_version.outputs.new_version_tag }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      run_build: ${{ steps.check_version.outputs.run_build }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for new version
        id: check_version
        run: |
          # خواندن نسخه از Makefile داخل پوشه پکیج
          MAKEFILE_PATH="${{ env.PACKAGE_DIR }}/Makefile"
          if [ ! -f "$MAKEFILE_PATH" ]; then
            echo "Makefile not found at $MAKEFILE_PATH"
            exit 1
          fi
          
          # استخراج نسخه و ریلیز با استفاده از awk
          PKG_VERSION=$(grep -m 1 'PKG_VERSION:=' "$MAKEFILE_PATH" | awk -F':=' '{print $2}' | xargs)
          PKG_RELEASE=$(grep -m 1 'PKG_RELEASE:=' "$MAKEFILE_PATH" | awk -F':=' '{print $2}' | xargs)
          CURRENT_TAG="v${PKG_VERSION}-${PKG_RELEASE}"
          echo "Current version from Makefile: ${CURRENT_TAG}"

          # بررسی وجود تگ در ریپازیتوری
          if git rev-parse "${CURRENT_TAG}" >/dev/null 2>&1; then
            echo "Tag ${CURRENT_TAG} already exists. No new build needed."
            echo "run_build=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected: ${CURRENT_TAG}. Proceeding with build."
            echo "run_build=true" >> $GITHUB_OUTPUT
            echo "new_version_tag=${CURRENT_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Create new release
        id: create_release
        if: steps.check_version.outputs.run_build == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.check_version.outputs.new_version_tag }}
          name: Release ${{ steps.check_version.outputs.new_version_tag }}
          body: "Automated release for Broadlink NG. IPK files for various architectures are attached."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # --- جاب دوم: کامپایل پکیج برای معماری‌های مختلف ---
  build_package:
    name: Build for ${{ matrix.arch }}
    needs: check_and_release
    if: needs.check_and_release.outputs.run_build == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # لیست کامل SDK ها برای معماری‌های مختلف بر اساس OpenWrt 23.05 (پایدار)
        # می‌توانید این لیست را بر اساس نیاز خود تغییر دهید
        include:
          - arch: "x86_64"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/x86/64/openwrt-sdk-23.05.3-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          - arch: "aarch64_cortex-a53"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/mediatek/filogic/openwrt-sdk-23.05.3-mediatek-filogic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          - arch: "aarch64_cortex-a72"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/bcm27xx/bcm2711/openwrt-sdk-23.05.3-bcm27xx-bcm2711_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a7_neon-vfpv4"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/ipq40xx/generic/openwrt-sdk-23.05.3-ipq40xx-generic_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz"
          - arch: "arm_cortex-a15_neon-vfpv4"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/ipq806x/generic/openwrt-sdk-23.05.3-ipq806x-generic_gcc-12.3.0_musl_eabi.Linux-x86_64.tar.xz"
          - arch: "mips_24kc"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/ath79/generic/openwrt-sdk-23.05.3-ath79-generic_gcc-12.3.0_musl.Linux-x86_64.tar.xz"
          - arch: "mipsel_24kc"
            sdk_url: "https://downloads.openwrt.org/releases/23.05.3/targets/ramips/mt7621/openwrt-sdk-23.05.3-ramips-mt7621_gcc-12.3.0_musl.Linux-x86_64.tar.xz"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses5-dev libssl-dev python3 python3-distutils rsync unzip zlib1g-dev file wget
      
      - name: Cache OpenWrt SDK
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: openwrt-sdk
          key: openwrt-sdk-23.05.3-${{ matrix.arch }}

      - name: Download and setup OpenWrt SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          wget -q -O openwrt-sdk.tar.xz "${{ matrix.sdk_url }}"
          mkdir -p openwrt-sdk
          tar -xJf openwrt-sdk.tar.xz -C openwrt-sdk --strip-components=1

      - name: SSH connection for debugging
        if: github.event.inputs.ssh == 'true'
        uses: mxschmitt/action-tmate@v3

      - name: Compile the package
        id: compile
        run: |
          SDK_PATH=$PWD/openwrt-sdk
          # کپی کردن پوشه پکیج به داخل SDK
          cp -r $GITHUB_WORKSPACE/$PACKAGE_DIR $SDK_PATH/package/
          
          cd $SDK_PATH
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          
          echo "Compiling package ${{ env.PACKAGE_DIR }}..."
          make package/$PACKAGE_DIR/compile -j$(nproc)
          
          # خواندن نام پکیج از Makefile برای پیدا کردن فایل ipk
          PKG_NAME_FROM_MAKEFILE=$(grep -m 1 'PKG_NAME:=' "package/${{ env.PACKAGE_DIR }}/Makefile" | awk -F':=' '{print $2}' | xargs)
          echo "Package name from Makefile is: ${PKG_NAME_FROM_MAKEFILE}"

          IPK_PATH=$(find $PWD/bin/packages -type f -name "${PKG_NAME_FROM_MAKEFILE}*.ipk")
          if [ -z "$IPK_PATH" ]; then
            echo "::error::IPK file not found!"
            exit 1
          fi
          echo "Found IPK at: ${IPK_PATH}"
          
          echo "ipk_path=${IPK_PATH}" >> $GITHUB_OUTPUT
          echo "pkg_name=${PKG_NAME_FROM_MAKEFILE}" >> $GITHUB_OUTPUT

      - name: Upload IPK to the release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.check_and_release.outputs.upload_url }}
          asset_path: ${{ steps.compile.outputs.ipk_path }}
          asset_name: ${{ steps.compile.outputs.pkg_name }}_${{ needs.check_and_release.outputs.new_version_tag }}_${{ matrix.arch }}.ipk
          asset_content_type: application/vnd.debian.binary-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
